package autogenerated

import java.io.InputStream

class LexerAnalyzer(private val stream: InputStream) {
	var position: Int = 0
	var currentChar: Int = -1
	var token: Token = Token.EOF
	var tokenValue: String = ""
	var tokenText: StringBuilder = StringBuilder()
	init {
		nextChar()
		nextToken()
	}
	
	fun nextToken(): Unit {
		skipWhitespaces()
		var string = ""
		var last: Char
		while (!currentChar.toChar().isWhitespace()) {
			if (currentChar < 0) {
				string = tokenText.toString()
				tokenText.clear()
				token = Token.EOF
				tokenValue = "EOF"
				break
			}
	
			last = currentChar.toChar()
			string = tokenText.toString()
			tokenText.append(currentChar.toChar())
			if (string == "/" || string == ")" || string.matches("[0-9]+".toRegex()) || string == "*" || string.matches("[a-zA-Z][a-zA-Z0-9]*".toRegex()) || string == "(" || string == ";" || string == "^" || string == "=" || string == "+" || string == "-") {
				nextChar()
				if (currentChar < 0 || currentChar.toChar().isWhitespace()) {
					string = tokenText.toString()
					tokenText.clear()
					break
				}
	
			} else {
				tokenText.clear()
				tokenText.append(last)
				nextChar()
				break
			}
	
	
		}
	
		if (string == "/") {
			token = Token.DIV
			tokenValue = "/"
			return
		}
	
		if (string == ")") {
			token = Token.RB
			tokenValue = ")"
			return
		}
	
		if (string.matches("[0-9]+".toRegex())) {
			token = Token.NUMBER
			tokenValue = "/[0-9]+/"
			return
		}
	
		if (string == "*") {
			token = Token.MULT
			tokenValue = "*"
			return
		}
	
		if (string.matches("[a-zA-Z][a-zA-Z0-9]*".toRegex())) {
			token = Token.VARIABLE
			tokenValue = "/[a-zA-Z][a-zA-Z0-9]*/"
			return
		}
	
		if (string == "(") {
			token = Token.LB
			tokenValue = "("
			return
		}
	
		if (string == ";") {
			token = Token.SEMI
			tokenValue = ";"
			return
		}
	
		if (string == "^") {
			token = Token.POW
			tokenValue = "^"
			return
		}
	
		if (string == "=") {
			token = Token.EQ
			tokenValue = "="
			return
		}
	
		if (string == "+") {
			token = Token.PLUS
			tokenValue = "+"
			return
		}
	
		if (string == "-") {
			token = Token.MINUS
			tokenValue = "-"
			return
		}
	
	}
	
	private fun nextChar(): Unit {
		currentChar = stream.read()
		position++
	}
	
	private fun skipWhitespaces(): Unit {
		while (currentChar.toChar().isWhitespace()) {
			nextChar()
		}
	
	}
}