package calculator.autogenerated

import java.io.InputStream

class CalculatorLexerAnalyzer(private val stream: InputStream, ) {
	var position: Int = 0
	var currentChar: Int = -1
	var token: CalculatorToken = CalculatorToken.EOF
	var tokenValue: String = ""
	var tokenText: StringBuilder = StringBuilder()
	
	init {
		nextChar()
		nextToken()
	}
	
	fun nextToken(): Unit {
		skipWhitespaces()
		var string = ""
		var last: Char
		while (!currentChar.toChar().isWhitespace()) {
			if (currentChar < 0) {
				string = tokenText.toString()
				tokenText.clear()
				token = CalculatorToken.EOF
				tokenValue = "EOF"
				break
			}
	
			last = currentChar.toChar()
			string = tokenText.toString()
			tokenText.append(currentChar.toChar())
			if (tokenText.toString() == "EPS" || tokenText.toString() == "EOF" || tokenText.toString() == "+" || tokenText.toString() == "-" || tokenText.toString() == "*" || tokenText.toString() == "/" || tokenText.toString() == "(" || tokenText.toString() == ")" || tokenText.toString().matches("[0-9]+".toRegex())) {
				nextChar()
				if (currentChar < 0 || currentChar.toChar().isWhitespace()) {
					string = tokenText.toString()
					tokenText.clear()
					break
				}
	
			} else {
				tokenText.clear()
				tokenText.append(last)
				nextChar()
				break
			}
	
	
		}
	
		if (string == "EPS") {
			token = CalculatorToken.EPS
			tokenValue = string
			return
		}
	
		if (string == "EOF") {
			token = CalculatorToken.EOF
			tokenValue = string
			return
		}
	
		if (string == "+") {
			token = CalculatorToken.PLUS
			tokenValue = string
			return
		}
	
		if (string == "-") {
			token = CalculatorToken.MINUS
			tokenValue = string
			return
		}
	
		if (string == "*") {
			token = CalculatorToken.MULT
			tokenValue = string
			return
		}
	
		if (string == "/") {
			token = CalculatorToken.DIV
			tokenValue = string
			return
		}
	
		if (string == "(") {
			token = CalculatorToken.LB
			tokenValue = string
			return
		}
	
		if (string == ")") {
			token = CalculatorToken.RB
			tokenValue = string
			return
		}
	
		if (string.matches("[0-9]+".toRegex())) {
			token = CalculatorToken.NUMBER
			tokenValue = string
			return
		}
	
	}
	
	private fun nextChar(): Unit {
		currentChar = stream.read()
		position++
	}
	
	private fun skipWhitespaces(): Unit {
		while (currentChar.toChar().isWhitespace()) {
			nextChar()
		}
	
	}
}