package lab2

import antlrgenerated.ParserGeneratorLexer
import antlrgenerated.ParserGeneratorParser
import autogenerated.LexerAnalyzer
import autogenerated.Parser
import generator.ParserGenerator
import generator.ParserGeneratorVisitorImpl
import org.antlr.v4.runtime.CharStreams
import org.antlr.v4.runtime.CommonTokenStream
import java.io.File

fun main() {
    val inputGrammar = File("lab2", "grammar")
    val stream = CharStreams.fromStream().trimIndent().byteInputStream())
    val parser = ParserGeneratorParser(CommonTokenStream(ParserGeneratorLexer(stream)))
    val tree = parser.start()
    val visitor = ParserGeneratorVisitorImpl()
    visitor.visitStart(tree)

    ParserGenerator().generate(visitor.data, "src/main/kotlin/autogenerated")

    val myParser = Parser(LexerAnalyzer("(2 + 4) * 10 / 20".byteInputStream()))
    val myTree = myParser.parse()
    println(myTree)
}