package calculator

import antlrgenerated.ParserGeneratorLexer
import antlrgenerated.ParserGeneratorParser
import generator.ParserGenerator
import generator.ParserGeneratorVisitorImpl
import org.antlr.v4.runtime.CharStreams
import org.antlr.v4.runtime.CommonTokenStream
import java.io.File

fun main() {
    val inputGrammarPath = "src/test/kotlin/calculator/grammarCalculator"
    val outputPath = "src/test/kotlin/calculator/autogenerated"
    val inputGrammar = File(inputGrammarPath)
    val stream = CharStreams.fromStream(inputGrammar.inputStream())
    val parser = ParserGeneratorParser(CommonTokenStream(ParserGeneratorLexer(stream)))
    val tree = parser.start()
    val visitor = ParserGeneratorVisitorImpl()
    visitor.visitStart(tree)

    ParserGenerator().generate(visitor.data, outputPath, "calculator")
}